name: Firestarter CI
on:
  push:
    branches:
    - main
    paths-ignore:
    - '**.md'
    - '**.sh'
    - '.gitignore'
    - 'docs/**'
    - 'documents/**'
    - 'test/**'
    - 'images/**'
    - '.github/**'
    - '.vscode/**'
    - '.editorconfig/**'
    - 'tools/**'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio

      - uses: actions/setup-python@v4

      # - name: install gh
      #   run: apt update && apt install gh
      
      - name: Generate release version
        id: version
        run: .github/scripts/update_version.py

      - uses: stefanzweifel/git-auto-commit-action@v5
        # with:
        #   tagging_message: ${{ steps.version.outputs.version }}
        # env:
        #   GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      - name: Install PlatformIO Core
        run: pip install --upgrade platformio

      - name: Build PlatformIO Project
        run: pio run

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: .pio/build/**/firestarter_*.hex        
          tag_name: ${{ steps.version.outputs.version }}
          make_latest: true
          # token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
